--1
SELECT PRODUCTNAME, UNITPRICE
FROM PRODUCTS
WHERE UNITPRICE = (SELECT MAX(UNITPRICE)
                        FROM PRODUCTS);

--2
SELECT ORDERID, SHIPNAME, ShipAddress, SHIPVIA
FROM ORDERS
WHERE SHIPVIA = (SELECT SHIPPERID
                 FROM SHIPPERS
                 WHERE SHIPPERID = 3);

--3
SELECT ORDERID
FROM [ORDER DETAILS]
WHERE PRODUCTID = (SELECT PRODUCTID
                   FROM PRODUCTS
                   WHERE PRODUCTID = 34);

--4
SELECT E.FIRSTNAME, E.LASTNAME
FROM ORDERS AS O
LEFT JOIN Employees AS E
    ON O.EMPLOYEEID = E.EMPLOYEEID 
WHERE ORDERID = 10266;

SELECT FIRSTNAME, LASTNAME
FROM EMPLOYEES
WHERE EmployeeID = (SELECT EmployeeID
                    FROM ORDERS
                    WHERE ORDERID = 10266);

--5
SELECT C.CONTACTNAME
FROM ORDERS AS O
INNER JOIN CUSTOMERS AS C
    ON O.CustomerID = C.CustomerID 
WHERE O.ORDERID = 10266;

SELECT CONTACTNAME
FROM CUSTOMERS
WHERE CUSTOMERID = (SELECT CUSTOMERID
                    FROM ORDERS
                    WHERE ORDERID = 10266);

